# Generated by Django 3.1.3 on 2020-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201114_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='can_access_documents',
            field=models.BooleanField(default=False),
        ),
    ]
