# Generated by Django 3.1.3 on 2020-11-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_can_access_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-contact_date']},
        ),
        migrations.AddField(
            model_name='contact',
            name='activly_interested',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='can_access_documents',
            field=models.BooleanField(default=False, verbose_name='Docs access'),
        ),
    ]
