# Generated by Django 3.1.3 on 2020-11-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20201116_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='activly_interested',
        ),
        migrations.AddField(
            model_name='contact',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
    ]
