# Generated by Django 3.1.3 on 2020-11-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20201116_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='outdated',
        ),
    ]
