# Generated by Django 3.1.3 on 2020-11-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingfile',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='listings/files/'),
        ),
    ]
