# Generated by Django 3.1.3 on 2020-11-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201113_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingfile',
            name='file',
            field=models.FileField(default=None, upload_to='listings/files/'),
        ),
    ]
