# Generated by Django 3.1.3 on 2020-11-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingtocustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_for',
            field=models.CharField(choices=[('S', 'Sell'), ('R', 'Rent')], default='S', max_length=5),
        ),
    ]
