# Generated by Django 3.1.3 on 2020-11-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_listing_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.listingtype', verbose_name='Type'),
        ),
    ]
