# Generated by Django 3.1.3 on 2020-11-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20201116_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='Monument Protected'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_for',
            field=models.CharField(choices=[('S', 'Sell'), ('R', 'Rent')], default='S', max_length=5),
        ),
    ]
