# Generated by Django 3.1.3 on 2020-11-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20201121_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveIntegerField(default=2, verbose_name='Bathrooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveIntegerField(default=2, verbose_name='Bedrooms'),
            preserve_default=False,
        ),
    ]
