# Generated by Django 3.1.3 on 2020-11-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_listing_free_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='list_date',
        ),
    ]
