# Generated by Django 3.1.3 on 2020-12-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20201203_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.FloatField(verbose_name='m²'),
        ),
    ]
