# Generated by Django 3.1.3 on 2020-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20201203_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_for',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sell')], default='S', max_length=5, verbose_name='Listing for'),
        ),
    ]
