# Generated by Django 3.1.3 on 2020-11-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20201121_1854'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='listingfile',
            name='file',
            field=models.FileField(default=None, upload_to='listings/files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='listingfile',
            name='for_customer',
            field=models.BooleanField(default=True, verbose_name='For customers'),
        ),
        migrations.AlterField(
            model_name='listingfile',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.listing', verbose_name='Listing'),
        ),
        migrations.AlterField(
            model_name='listingfile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='listingfile',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='listingfile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
    ]
